title: Blue Hat Security
description: Defensive Security dive-in and tutorials

remote_theme: brianmaierjr/long-haul

paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
header: large

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 50

navigation:
  - title: Home
    url: /index.html
  - title: Blog
    url: /articles
  - title: About
    url: /about

social:
  github: ramonatame
  twitter: RamonaTame
  linkedin: ramona-tame-328539ab
